name: Verify

on: [ push ]

env:
  LEFTHOOK: 0

jobs:
  verify:
    uses: meza/shared-github-workflows/.github/workflows/default-node-npm-ci.yml@cf630bfc334354a662e60d05adaf7615b7399b00 # main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
        test: false
        node-version: "latest"
        junit-report-path: "reports/junit.xml"
        cobertura-report-path: "reports/coverage/cobertura-coverage.xml"
