name: Release

on:
  schedule:
    - cron: '0 9 * * 2'
      timezone: Europe/London
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

env:
  LEFTHOOK: 0

jobs:
  verify:
    runs-on: ubuntu-slim
    name: 🔎 Lint and Test
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Run Tests
        run: npm run ci
      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - env:
          NEED_RELEASE: ${{ steps.get-next-version.outputs.new-release-published }}
        run: echo "Need release? $NEED_RELEASE" >> "$GITHUB_STEP_SUMMARY"

  build:
    strategy:
      matrix:
        os: [ meza-ubuntu-slim, meza-windows-slim, macos-latest ]
    runs-on: ${{ matrix.os }}
    needs: [ verify ]
    if: needs.verify.outputs.new-release-published == 'true'
    name: Build binaries for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Python 3.10.6
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '>=3.10.6'
      - name: Install dependencies
        run: python3 -m pip install setuptools
      - name: Set up node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci --no-audit --no-fund
      - name: Set Windows environment
        if: matrix.os == 'meza-windows-slim'
        run: |
          echo 'GYP_MSVS_VERSION=2015' >> $Env:GITHUB_ENV
          echo 'GYP_MSVS_OVERRIDE_PATH=C:\\Dummy' >> $Env:GITHUB_ENV
      - name: Set version
        run: npm version --no-git-tag-version ${{ needs.verify.outputs.new-release-version }}
      - name: "Build"
        run: npm run build && npm run prebuilds
      - name: "Test"
        run: npm run test
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: prebuilds-${{ matrix.os }}
          path: prebuilds
  release:
    needs: [ verify, build ]
    if: needs.verify.outputs.new-release-published == 'true'
    name: Release
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci --no-audit --no-fund
      - name: "Build"
        run: npm run build
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: prebuilds-meza-windows-slim
          path: prebuilds
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: prebuilds-meza-ubuntu-slim
          path: prebuilds
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: prebuilds-macos-latest
          path: prebuilds
      - name: 🚀 Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run release
